name: map_cluster
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  google_maps_flutter: ^2.9.0
  carousel_slider: ^5.0.0
  logger: ^2.4.0
  geolocator: ^13.0.1
  shimmer: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.12


flutter:


  uses-material-design: true

  assets:
    - assets/person.png

 